name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make
      
    - name: Upload
      uses: actions/upload-artifact@v3.1.3
      with:
        path: networkhelper.iso
        if-no-files-found: error
